require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequisitionsController do

  # This should return the minimal set of attributes required to create a valid
  # Requisition. As you add validations to Requisition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all requisitions as @requisitions" do
      requisition = Requisition.create! valid_attributes
      get :index
      assigns(:requisitions).should eq([requisition])
    end
  end

  describe "GET show" do
    it "assigns the requested requisition as @requisition" do
      requisition = Requisition.create! valid_attributes
      get :show, :id => requisition.id.to_s
      assigns(:requisition).should eq(requisition)
    end
  end

  describe "GET new" do
    it "assigns a new requisition as @requisition" do
      get :new
      assigns(:requisition).should be_a_new(Requisition)
    end
  end

  describe "GET edit" do
    it "assigns the requested requisition as @requisition" do
      requisition = Requisition.create! valid_attributes
      get :edit, :id => requisition.id.to_s
      assigns(:requisition).should eq(requisition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Requisition" do
        expect {
          post :create, :requisition => valid_attributes
        }.to change(Requisition, :count).by(1)
      end

      it "assigns a newly created requisition as @requisition" do
        post :create, :requisition => valid_attributes
        assigns(:requisition).should be_a(Requisition)
        assigns(:requisition).should be_persisted
      end

      it "redirects to the created requisition" do
        post :create, :requisition => valid_attributes
        response.should redirect_to(Requisition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requisition as @requisition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisition.any_instance.stub(:save).and_return(false)
        post :create, :requisition => {}
        assigns(:requisition).should be_a_new(Requisition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisition.any_instance.stub(:save).and_return(false)
        post :create, :requisition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requisition" do
        requisition = Requisition.create! valid_attributes
        # Assuming there are no other requisitions in the database, this
        # specifies that the Requisition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Requisition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => requisition.id, :requisition => {'these' => 'params'}
      end

      it "assigns the requested requisition as @requisition" do
        requisition = Requisition.create! valid_attributes
        put :update, :id => requisition.id, :requisition => valid_attributes
        assigns(:requisition).should eq(requisition)
      end

      it "redirects to the requisition" do
        requisition = Requisition.create! valid_attributes
        put :update, :id => requisition.id, :requisition => valid_attributes
        response.should redirect_to(requisition)
      end
    end

    describe "with invalid params" do
      it "assigns the requisition as @requisition" do
        requisition = Requisition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisition.any_instance.stub(:save).and_return(false)
        put :update, :id => requisition.id.to_s, :requisition => {}
        assigns(:requisition).should eq(requisition)
      end

      it "re-renders the 'edit' template" do
        requisition = Requisition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisition.any_instance.stub(:save).and_return(false)
        put :update, :id => requisition.id.to_s, :requisition => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requisition" do
      requisition = Requisition.create! valid_attributes
      expect {
        delete :destroy, :id => requisition.id.to_s
      }.to change(Requisition, :count).by(-1)
    end

    it "redirects to the requisitions list" do
      requisition = Requisition.create! valid_attributes
      delete :destroy, :id => requisition.id.to_s
      response.should redirect_to(requisitions_url)
    end
  end

end
